// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Header} from "./components/Header";
import React from "react";
import QueryProvider from "./components/QueryProvider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "My Site",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }) {
    return (
        <html lang="ru" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <QueryProvider>
                <Header/>
                {children}
        </QueryProvider>
        </body>
        </html>
    );
}
